server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: none
  redis:
    ssl: false
#security:
#  basic:
#    enabled: false

#foryou:
#  security:
#    browser:
#      loginPage: /demoLogin.html
#    validateCode:
#      imageCode:
#        url: /user,/user/*
#        width: 500

